### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by karstengresch**

### CODE REVIEW

**Comment by danieloh30** [comment]
@karstengresch As I mentioned earlier, can you please create a new PR in ocp-4.4 branch instead of the master?  The current CCN is not referring to the master. If you can't, I will rectify the typo directly.

**Comment by danieloh30** [comment]
Close it to use an inappropriate branch

**Comment by karstengresch** [comment]
Sorry, @danieloh30, didn't see your message before, created new PRs in the desired branch.

**Comment by danieloh30** [comment]
@karstengresch No worries. Thanks for your contribution!!!

**Pull request closed without merging**
