### PR TITLE
we create the configuration first then build

### PR DESCRIPTION
**Pull request by jbrannst**

### CODE REVIEW

**Comment by danieloh30** [comment]
It means developers will build an application container image based on the OpenJDK image via binary build.

**Comment by jbrannst** [comment]
So write that in the guide. We are not building at that step, we do the build in the step after. 

Please read it yourself and you will see it is obviously incorrect today.

**Comment by danieloh30** [comment]
That's not incorrect. But it might be confused if a dev has no experiences of OpenShift, Linux Container.

I will update the context a bit explicitly as below:
Create a build configuration for your application using OpenJDK base container image in OpenShift:

**Comment by jbrannst** [comment]
Perfect, then it will become correct

Den tors 16 jan. 2020 14:08Daniel Oh <notifications@github.com> skrev:

**Pull request closed without merging**
